"""empty message

Revision ID: 732a90898842
Revises: 
Create Date: 2023-05-14 15:33:14.318660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732a90898842'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('ffmpeg_directory', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('hardware_transcoding', sa.String(length=16), nullable=True),
    sa.Column('metadata_sources', sa.String(length=128), nullable=True),
    sa.Column('spotify_api', sa.String(length=128), nullable=True),
    sa.Column('genius_api', sa.String(length=128), nullable=True),
    sa.Column('auth', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('auth_username', sa.String(length=128), nullable=True),
    sa.Column('auth_password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('database',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filepath', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('artist', sa.String(length=64), nullable=True),
    sa.Column('album', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('cover', sa.String(length=256), nullable=True),
    sa.Column('audio_id', sa.String(length=128), nullable=True),
    sa.Column('youtube_id', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath'),
    sa.UniqueConstraint('youtube_id')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('extension', sa.String(length=16), nullable=True),
    sa.Column('output_folder', sa.String(length=128), nullable=True),
    sa.Column('output_name', sa.String(length=32), nullable=True),
    sa.Column('bitrate', sa.String(length=8), nullable=True),
    sa.Column('resolution', sa.String(length=16), nullable=True),
    sa.Column('default', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('proxy_status', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('proxy_type', sa.String(length=16), nullable=True),
    sa.Column('proxy_username', sa.String(length=128), nullable=True),
    sa.Column('proxy_password', sa.String(length=128), nullable=True),
    sa.Column('proxy_address', sa.String(length=128), nullable=True),
    sa.Column('proxy_port', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('templates')
    op.drop_table('database')
    op.drop_table('config')
    # ### end Alembic commands ###
